Webアプリ開発（2-1,2-2）
nishinoa/test1 pull request #10
Opened 2022-05-27 08:30 UTC by nishinoa

@山川宏賢 @yanagi-m @田中みつき
Webアプリ開発の「2-1. カウント結果を保存できるようにする」「2-2. 前回保存時のカウンターを表示できるようにする」について対応を行いましたので、ご確認の程よろしくお願いします。
※「2-1. カウント結果を保存できるようにする」と「2-2. 前回保存時のカウンターを表示できるようにする」は別ブランチで対応するルールになっていたかと思いますが、似たような対応だったので纏めて同一ブランチで対応しました。

2022-05-27 09:34 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき
画面キャプチャを添付し忘れましたので、添付します。

![image](https://user-images.githubusercontent.com/92168753/170673150-4cbba274-7704-443d-b645-77910d641a55.png)

2022-05-30 01:00 UTC, hyamakawa requested changes
@nishinoa 

確認しました。コメントしたので対応お願いいたします。

2022-05-30 01:00 UTC, hyamakawa commented on webdevelop/Code.js
> +  const SHEET_NAME = 'シート1'
SHEET_ID, SHEET_NAMEは2つの関数で固定になっているので、メンテナンス性考慮して、グローバル部分に変数定義してもいいのかな、と思いました。

2022-05-30 11:42 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-05-30 11:43 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-05-30 11:47 UTC, nishinoa commented
@hyamakawa @yanagi-m @田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-05-31 02:54 UTC, hyamakawa commented
@nishinoa LGTM!!

2022-05-31 10:13 UTC, MitsukiTanaka commented
@nishinoa LGTM!!

2022-05-31 10:14 UTC, yanagi-m commented
@nishinoa LGTM 🎉

2022-05-31 11:30 UTC, merged