Webアプリ開発（3-1）
nishinoa/test1 pull request #11
Opened 2022-06-04 10:24 UTC by nishinoa

@山川宏賢 @yanagi-m @田中みつき  
Webアプリ開発の「3-1. Vue.jsを導入して作り替える」について対応を行いましたので、ご確認の程よろしくお願いします。

2022-06-06 02:51 UTC, hyamakawa requested changes
@nishinoa 

ありがとうございます、確認しました。   
特に質問もなく、Vueにすんなり入れてる感じがすごい、さすがです。  
コメントしたので対応よろしくお願いいたします。

2022-06-06 02:51 UTC, hyamakawa commented on webdevelop/index.html
> +        mounted: function(){
mountedにした理由はなんでしょうかっ。
mountedでも問題ないとは思うのですが、ライフサイク的により手前でvalueに値が確定している方がいいのかなと思うので、createdの方がいいのかなーと思いました。

2022-06-06 02:51 UTC, hyamakawa commented on webdevelop/index.html
> +          value: null
上書きはされるのですが数字以外が入ると困ると思うので、初期値としては0がいいのかなと思いました。

2022-06-06 02:51 UTC, hyamakawa commented on webdevelop/index.html
> +            google.script.run.setSheetData(this.value);
課題にはなかったですが、以下を入れてみませんか？
・保存が成功した時は 保存したことがわかるメッセージを出力する
・保存が失敗した時は 保存失敗したことがわかるメッセージを出力する

2022-06-06 02:51 UTC, hyamakawa commented on webdevelop/index.html
> +            app.value = result;
`app.value ` ってなんですか？

2022-06-06 02:51 UTC, hyamakawa commented on webdevelop/index.html
> +          google.script.run.withSuccessHandler(function(result) {
意図しない挙動にならないように、errorになったときのロジックも書いておきます？

2022-06-06 02:51 UTC, hyamakawa commented on webdevelop/index.html
> +          reSet: function(){
ここに限った話ではないです。

``` javascript
xxx: function() {
  ...
}
```

は

``` javascript
xxx() {
  ...
}
```

にJavaScriptの仕組み的に書き換えられると思います。
functionって毎回書くのめんどくさいと思うので情報連携でした。

2022-06-06 10:51 UTC, nishinoa commented on webdevelop/index.html
> +        mounted: function(){
@hyamakawa 
createdはDOMが作成される前に呼ばれ、mountedはDOMが作成された後に呼ばれるのでmonuntedにしました。
ネットでも色々なサイトを調べましたが、初期処理はmountedで行うとしているサイトがほとんどでした。

2022-06-06 10:55 UTC, nishinoa commented on webdevelop/index.html
> +          value: null
@hyamakawa 
スプレッドシートの値が表示される前に、一瞬ですが「0」が表示されてしまう為、
見た目的に良くないと思い、nullで初期化しました。

2022-06-06 10:59 UTC, nishinoa commented on webdevelop/index.html
> +            app.value = result;
@hyamakawa 
53行目でVueのインスタンスを設定している変数です。
コールバック関数では「this」は参照出来ない為、「app」を参照するようにしました。
※実際に「this」を参照するようにして動かしましたが、うまく動作しませんでした。

2022-06-07 13:29 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-06-07 22:06 UTC, hyamakawa commented on webdevelop/index.html
> +          value: null
@nishinoa 

そういうことですね、理解しました。
おそらくそれは、スプレッドシートからデータを取得する処理が非同期で実行されているからなのかなと思いました。
カリキュラムでいう最後の課題で着手するところになります。
なので、この修正ではnullにしておいて、非同期処理を同期処理にする課題を着手する際に「0」にするといいかと思いました（当初コメントした通り、ある変数にいろんなパターンの値が入ることは極力避けるべきだと思うので）。
また、mountedで処理しているのも、もしかしたら関係あるかもしれませんね。

2022-06-07 22:06 UTC, hyamakawa commented on webdevelop/index.html
> +        mounted: function(){
@nishinoa 

そうなんですね、初期処理がどういうものかによってパターンが分かれそうですね（データが準備されるまでの間に、どういう画面描画をしたいか）。
mountedで問題ありませんっ。

2022-06-07 22:06 UTC, hyamakawa commented on webdevelop/index.html
> +            app.value = result;
@nishinoa 

そうなんですね、理解しました。
app.valueで問題ございません。
gasで、かつ1ファイルでやってるというのが影響しているかもしれませんね。
通常のローカル開発では `app.xxx` とは使ってるケースを見たことがないので。

2022-06-07 22:16 UTC, hyamakawa reviewed
確認しました！
あとちょっとだけコメントしましたので、ご確認お願いします。

2022-06-07 22:16 UTC, hyamakawa commented on webdevelop/index.html
> +          try {
対応ありがとうございます。

tryでも問題ないのですが、 `withFailureHandler`を使用するイメージでコメントしてました。
https://tonari-it.com/gas-dialog-with-failure-handler/

どちらでいくかはお任せしますっ！

2022-06-07 22:16 UTC, hyamakawa commented on webdevelop/index.html
> +              google.script.run.setSheetData(this.value);
こちらも `withSuccessHandler ` `withFailureHandler ` を使うイメージでコメントしてました。

`withFailureHandler` の部分はお任せします！
が、成功した際のロジックは createdでやってるロジックと合わせて `withSuccessHandler` を使いたいなと思うのですが、使えなかった感じでしょうか。

2022-06-08 11:29 UTC, nishinoa commented on webdevelop/index.html
> +          value: null
@hyamakawa 
createdにしてもmountedの時と動きは変わりませんでした。
※スプレッドシートの値が表示される前に、一瞬「0」が表示される。

2022-06-08 11:37 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。
※createdをmountedに戻しました。
※「value」の初期値を0からnullに戻しました。

2022-06-09 00:34 UTC, hyamakawa commented
@nishinoa LGTM 🙆‍♂️

2022-06-09 12:06 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき
明日から次の課題に取り組みたいのですが、柳原さんと田中さんのレビューはいつ頃になりそうでしょうか？
masterにマージしてしまいたいので、なる早でお願いしたいです。

2022-06-09 23:30 UTC, hyamakawa commented
@nishinoa 

マージしないと次の課題進めないわけではないので、以下やり方をやってみてもいいかもです。

・webdevelop5 からさらにブランチを切って課題を進める
・プルリク時のマージ先はwebdevelop5にする

※実際のプロジェクトでもちょくちょく発生することではあるので

2022-06-10 00:19 UTC, yanagi-m commented
@nishinoa すみません、本日もしくは来週月曜日になりそうです 🙇 
次の課題に着手されるようでしたら、👆で山川さんが書かれているやり方で進めていただけると幸いです 🙇

2022-06-10 09:01 UTC, yanagi-m commented
@nishinoa すみません、遅くなりました。LGTM!

2022-06-10 09:21 UTC, merged