Webアプリ開発（3-2）
nishinoa/test1 pull request #12
Opened 2022-06-12 10:06 UTC by nishinoa

@山川宏賢 @yanagi-m @田中みつき
Webアプリ開発の「3-2. Vuetifyを導入して見た目をいい感じにしてみる」について対応を行いましたので、ご確認の程よろしくお願いします。

![image](https://user-images.githubusercontent.com/92168753/173228136-aaf4c62a-696c-4fbc-a8dd-569fa72c7fb6.png)

2022-06-14 05:52 UTC, hyamakawa requested changes
@nishinoa 

見ました、コメントしたので確認お願いします。

2022-06-14 05:52 UTC, hyamakawa commented on webdevelop/index.html
> +            <v-text-field v-model="value" class="input-center" readonly></v-text-field>
閉じタグを省略できるものがあるので、意識してみてください。
https://agohack.com/html-closetags/

基本的には、間に挟むものがなければ省略できる、という認識でいいのかな〜と経験的に思います。
（省略できないものは大体想定した動きにならないので気づく）

2022-06-14 05:52 UTC, hyamakawa commented on webdevelop/index.html
> +            <v-text-field v-model="value" class="input-center" readonly></v-text-field>
この行に関しては閉じタグを省略できるので、対応お願いしますっ

2022-06-14 05:52 UTC, hyamakawa commented on webdevelop/index.html
> +        <v-row justify="center" align-content="center">
`<v-row></v-row>` のみで囲まれたものと `<v-row><v-col></v-col></v-row>` で囲まれたものがありますが、何か使い分けされてますか？

2022-06-14 05:52 UTC, hyamakawa commented on webdevelop/index.html
> +          <v-btn v-on:click="countUp" width="4" color="red">+</v-btn>
v-row, v-colを使いこなせられれば `width ` を使うことはなくなると思います。  
そして、PC画面でもスマホ画面でも良い感じに調整してくれる様になると思いますので、試してみてください。

2022-06-14 05:52 UTC, hyamakawa commented on webdevelop/index.html
> +            <v-text-field v-model="value" class="input-center" readonly></v-text-field>
input-centerですが、この部品しかCSS当てていないので個別にstyleを当てる方法でもいいのかなと思いました。

styleという属性があって、それで個別に当てることができると思います。

```
例： <v-text-field style="..." />
```

2022-06-14 11:33 UTC, nishinoa commented on webdevelop/index.html
> +        <v-row justify="center" align-content="center">
@hyamakawa 
ボタンを<v-col></v-col>で囲んで幅を調整すると、位置が真ん中から少し左にずれてしまう為、
widthで調整するようにしました。

2022-06-14 12:26 UTC, nishinoa commented on webdevelop/index.html
> +            <v-text-field v-model="value" class="input-center" readonly></v-text-field>
@hyamakawa 
<v-text-field style="text-align: center">に修正しましたが、テキストの数字は中央寄せになりませんでした（下記参照）。
指定の仕方間違ってますか？

![image](https://user-images.githubusercontent.com/92168753/173576673-f3cfcafa-b91e-45ba-baa1-05d7524b6801.png)

2022-06-15 11:09 UTC, hyamakawa commented on webdevelop/index.html
> +        <v-row justify="center" align-content="center">
承知しました。
ちょっと特殊なことされてはいますが、一旦元のままで進めていただいて構いません。
この課題では、画面をいじるのに普通ならcssとかゴリゴリ描かないといけないけど、フレームワークを使えばcssとかある程度省略できるんだな、という感覚を養っていただければいいためです。
また余裕ある時にでも統一した作り（<v-col>を挟むか挟まないか）にチャレンジしてもらえるといいかなと思います。

2022-06-15 11:12 UTC, hyamakawa commented on webdevelop/index.html
> +            <v-text-field v-model="value" class="input-center" readonly></v-text-field>
v-text-fieldの中の数字を中央寄せしていたCSSだったんですね、気付いてませんでした。
できなければ深入りする必要はありません。
が、元々styleタグ内で書かれていた `input{ text-align: center; }`  を書いてもダメだったということですかね？
コメントに `text-align: center;` とだけ書かれていたので気になりました。

2022-06-15 11:12 UTC, hyamakawa commented
@nishinoa 

コメントしましたので確認お願いします！

2022-06-15 12:11 UTC, nishinoa commented on webdevelop/index.html
> +            <v-text-field v-model="value" class="input-center" readonly></v-text-field>
@hyamakawa 
input{text-align:center;}を指定してもダメでした。

2022-06-15 12:17 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-06-16 02:01 UTC, hyamakawa commented on webdevelop/index.html
> +            <v-text-field v-model="value" class="input-center" readonly></v-text-field>
😭

2022-06-16 02:02 UTC, hyamakawa commented on webdevelop/index.html
> +            <v-text-field v-model="value" class="input-center" readonly>
これでエラーでないんですね。。。

閉じタグ省略する際は <v-text-field ..... /> です。

2022-06-16 02:03 UTC, hyamakawa commented on webdevelop/index.html
> +    <script src="https://cdn.jsdelivr.net/npm/vuetify@2.6/dist/vuetify.js"></script>
この2つもついでに閉じタグ省略しちゃいますか？

2022-06-16 02:05 UTC, hyamakawa commented on webdevelop/index.html
> +    <script src="https://cdn.jsdelivr.net/npm/vuetify@2.6/dist/vuetify.js"></script>
scripタグは省略しちゃだめらしいので無視してください！

2022-06-16 02:06 UTC, hyamakawa requested changes
@nishinoa 

v-text-fieldの閉じタグ対応だけしてマージしちゃってください :bow

2022-06-16 11:02 UTC, merged