Webアプリ開発（4-3,4-4,4-5）
nishinoa/test1 pull request #14
Opened 2022-06-24 11:58 UTC by nishinoa

@山川宏賢 [@yanagi-m](https://github.com/yanagi-m) @田中みつき  
Webアプリ開発の「4-3. DBに値を登録・更新する関数を作る」、「4-4. DBから値を取得する関数を作る」、「4-5. 脱スプレッドシート をして、DB とデータをやりとりできるようにする」について対応を行いましたので、ご確認の程よろしくお願いします。

2022-06-26 05:15 UTC, hyamakawa requested changes
@nishinoa 

確認しました。
特に質問なくここまでできるの、すごいですっ、さすがです。

コメントしたのでご確認・ご対応お願いします。

2022-06-26 05:15 UTC, hyamakawa commented on webdevelop/Code.js
> +    connection.close();
57行目〜59行目、returnした後の処理として書いていますが、returnした時点で処理が終了すると思うので、実行されずに終了してしまわないですかね？

65行目〜67行目も同様。

2022-06-26 06:48 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき  
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-06-26 23:30 UTC, hyamakawa commented on webdevelop/Code.js
> +  sql += "insert into ";
コメント漏れてました。

キーに一致するレコードがなければinsert、あればupdateしてくれるSQLがあります。
それを使えばもう少しシンプルな形になりそうだなと思いました。

参考：https://dev.mysql.com/doc/refman/5.6/ja/insert-on-duplicate.html

2022-06-26 23:31 UTC, hyamakawa commented
@nishinoa 

returnのコメントに対する修正は確認いたしました。

追加でコメントしたのでご確認・ご対応お願いします。

2022-06-27 12:01 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-06-27 12:34 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。
※1回目の[928ab61]は誤りとなります。2回目の[e2b114f]で確認をお願いします。

2022-06-29 01:19 UTC, hyamakawa requested changes
@nishinoa 

確認しました。1点コメントしたので、ご確認・ご対応お願いします。
対応完了しましたら、マージしていただいて構いません。

2022-06-29 01:19 UTC, hyamakawa commented on webdevelop/index.html
> +          // saveCounter()を呼び出す
すごく細かいですが、コメント間違ってます？

2022-06-29 11:10 UTC, merged