Webアプリ開発（4-6）
nishinoa/test1 pull request #15
Opened 2022-07-03 10:58 UTC by nishinoa

@山川宏賢 @yanagi-m @田中みつき  
Webアプリ開発の「4-6. 非同期処理を同期処理に変え、ローディング機能を取り入れる」について対応を行いましたので、ご確認の程よろしくお願いします。

2022-07-03 23:53 UTC, hyamakawa requested changes
@nishinoa 

対応お疲れ様です！
確認しコメントしたので、ご確認・ご対応よろしくお願いします。

2022-07-03 23:53 UTC, hyamakawa commented on webdevelop/index.html
> +            }, 1000)
メージとしてはあってるのですが、処理が終わるまでの一定時間待つ、という対応は今回の課題の趣旨と少し異なります。

スキルカリキュラムにもある通り、やりたいことは非同期処理を同期処理に変えることです。

フロントエンドからをDBから値を取得する処理を呼び出すと、その処理が完了するまでフロントエンドでは待ってくれていないのが現状だと思います。それが非同期処理と言われているものです。
それを、DBから値を取得する処理が完了するまでフロントエンドで待機して、処理が完了したら、フロントエンド側の次の処理を実行する、というイメージです。

キーワードとしては `async` `await` `promise` あたりかなと思っています。

JavascriptPrimerにも詳しく書いているところありますね。
https://jsprimer.net/basic/async/

2022-07-03 23:53 UTC, hyamakawa commented on webdevelop/index.html
> +        </v-overlay>
ローディングを出す、出さないの制御部分に関しては、バッチリだと思います。

2022-07-04 11:11 UTC, nishinoa commented on webdevelop/index.html
> +            }, 1000)
@hyamakawa 
GASの教材の「4.Webアプリ編」に、withSuccessHandlerメソッドは「クライアントサイドからGAS関数を呼び出したのちの処理を設定できる」旨の記載があった為、withSuccessHandlerメソッドの引数にコールバック関数を指定することにより同期処理が実現出来ていると思ったのですが、この対応だけでは不十分なのでしょうか？

2022-07-04 11:32 UTC, hyamakawa commented on webdevelop/index.html
> +            }, 1000)
@nishinoa 

同期処理ができているとは言えないです。

現在mountedで行っている処理の流れを詳細に言うと、mountedの処理は DB取得処理を実行して終了しちゃってるんです。あくまで `withSuccessHandler ` で書いてることはイベントの登録処理になっていて、サーバーから結果が帰ってきたらapp.valueに値を詰めてねというイベントが書かれている。なので、mountedの処理が終わった後にイベント発火してるイメージ。

ですが、こんかいの課題でやりたいことは、さーばーの結果が帰ってくるまでmountedの処理を終わらせないことです。画面の動くで言うと、画面開いて、くるくるローディングが走って、ローディングが終わるとDBの結果が表示された画面がパッと表示される感じです。

文字だと伝えるの難しいですね、伝わりましたでしょうか。

2022-07-04 11:55 UTC, nishinoa commented on webdevelop/index.html
> +            }, 1000)
@hyamakawa 
すみません、スキル面カリキュラムの記載内容からそこまで読み取る事は出来ませんでした。
取り敢えずやりたい事はわかりました。

2022-07-05 11:19 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき  
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-07-06 07:53 UTC, hyamakawa requested changes
@nishinoa 

対応確認しました、コメントしたのでご確認・ご対応お願いします。

2022-07-06 07:53 UTC, hyamakawa commented on webdevelop/index.html
> +            setTimeout(() => {
setTimeoutは不要になったと思うので削除したいですよね。
なので、ローディングをオフにする処理も場所が変わりますね。

2022-07-06 11:34 UTC, nishinoa commented
@山川宏賢 @yanagi-m @田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-07-06 23:40 UTC, hyamakawa commented
@nishinoa LGTM 🙆‍♂️

2022-07-07 10:41 UTC, merged