Webアプリ開発2（3-2-1～3-2-3）
nishinoa/test1 pull request #19
Opened 2022-08-20 14:31 UTC by nishinoa

@山川宏賢@yanagi-m@田中みつき
Webアプリ開発2の「2-1. 書籍を一覧表示するコンポーネントを作成する（BookApp.vue）」、「2-2. 書籍の検索条件を入力できるコンポーネントを作成する（BookApp.vue）」、「2-3. 書籍の登録、更新内容を入力できるコンポーネントを作成する（BookApp.vue）」について対応しましたので、  
ご確認の程、よろしくお願いします。
※一覧に表示するデータについては、一旦固定値としています。

2022-08-22 00:26 UTC, hyamakawa requested changes
@nishinoa 

できましたね👍
確認しました。コメントしたのでご確認・ご対応よろしくお願いいたします。

※タスク単位に切ってる意味がなくなるので、次からはまとめてプルリクを控えていただけるとうれしいです

2022-08-22 00:26 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +        ></v-select>
開始タグと終了タグの間に何もないので、/> で閉じればいいと思います。

2022-08-22 00:26 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +                          </v-date-picker>
ここも /> で閉じればよいと思います。

2022-08-22 00:26 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +              <v-spacer></v-spacer>
ここも <v-spacer />

2022-08-22 00:26 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +                            v-model="textDate"
違いによりますが、ここはpickerDate なのかな？とおもいました。
また、dialogBookList.~~~という形ではないのですね。
何か理由あったりします？

2022-08-22 00:26 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +                        :return-value.sync="pickerDate"
textDateとpickerDateの違いはなんでしょうか。

2022-08-22 00:26 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +                            @input="formatDate(pickerDate)
YYYY-MM-DDの形から変えたい場合は、こちらを参考にしてもいいかもです。
https://vuetifyjs.com/ja/components/date-pickers/#section-66f85f0f8a2d5b9a

<v-text-field>の中で@blurを使って、変換してるみたいです。

2022-08-22 00:26 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +        <td>{{ bookList.buyer }}</td>
現在の方法で実現できているので無理に変更しなくてもいいのですが、`<td></td>` 使わずに実現する方がフレキシブルなアプリ（画面の大きさに合わせてvuetifyが勝手にいい感じにしてくれる）になります。

https://vuetifyjs.com/ja/components/data-tables/#crud-30a230af30b730e730f3

2022-08-22 00:26 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +      isLoading: true
初期値は基本の値を設定した方がいいと思うので、falseの方がいいかと思いました。
ローディング表示しているのが基本です、は多分違いますよね。

2022-08-22 00:26 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +    onClickEditIcon (bookList) {
引数には変数名である程度どういうデータが入っているのか予測できるようにした方がいいと思うので、名前を変えますか。bookとか。

listだと配列が入る項目なのかなと思ってしまいます。

2022-08-22 00:26 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +        item-text="category"
item-valueは設定していないのですね。
プルダウンで洗濯すると、searchCategoryには何が入りますか？

2022-08-22 13:26 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +                            @input="formatDate(pickerDate)
@hyamakawa 
DATE型のDB項目の設定形式が「YYYYMMDD」と勘違いしていた為、date-pickerの日付を「YYYY-MM-DD」形式から「YYYYMMDD」形式に変換する処理を入れましたが、形式変換は特に必要ない為、形式変換しないことにします。

2022-08-22 13:31 UTC, nishinoa commented
@山川宏賢@yanagi-m@田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-08-24 00:49 UTC, hyamakawa requested changes
@nishinoa 

確認しました。コメントしたのでご確認・ご対応よろしくお願いいたします。
また、1点お願いがあります。
プルリクで投げたコメントに対して返すようにしてませんか？
西埜さんが「どういう考えでそのように実装したのか」をもう少し理解したいためです。
何か理由があって意図して実装したのか、わかっていたけど漏れていただけなのか、単純に知らなかったのか、その辺りがわかると、また自分のコメントも違ってくるのかなと思ってますし、それを意識しながら学習をしていける方が学習効率は上がると思います。
Webアプリ開発の課題は難易度が低かったので気にしませんでしたが、Webアプリ開発2は一応最後のスキル磨き課題になっているのでココでしっかり身につけるようにしていきましょうっ。

よろしくお願いいたします🙏

2022-08-24 00:49 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +    this.isLoading = false
これはいらないですかね。

2022-08-24 00:49 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +                        :return-value.sync="pickerDate"
36行目の `<v-menu` から63行目 `</menu>`までのdatepickerの使い方、合ってないようにみえるんですよね。
今一度[vuetifyのdate-pickerページ](https://vuetifyjs.com/ja/components/date-pickers/#section-30c030a430a230ed30b0306830e130cb30e530fc)を見て、見直していただいてもいいですか？

2022-08-24 00:49 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +        {{ bookList.buyer }}
コメントにつけた参考サイト見ていただけてます？違う対応内容になるかと思います。

2022-08-24 00:49 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +        item-text="category"
こちらご回答よろしくお願いいたします。

2022-08-24 10:29 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +        ></v-select>
@hyamakawa 
該当箇所について修正しました。

2022-08-24 10:29 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +                          </v-date-picker>
@hyamakawa 
該当箇所について修正しました。

2022-08-24 10:29 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +              <v-spacer></v-spacer>
@hyamakawa 
該当箇所について修正しました。

2022-08-24 10:31 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +                            v-model="textDate"
@hyamakawa 
「dialogBookList.purchase_date」があるので、「textDate」は不要でした。

2022-08-24 10:35 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +                        :return-value.sync="pickerDate"
@hyamakawa 
＞＞textDateとpickerDateの違いはなんでしょうか。
→「v-date-picker」で選択した日付を「v-text-field」に設定するようにする為に分けたのですが、「dialogBookList.purchase_date」があるので、「textDate」は不要でした。

2022-08-24 10:44 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +      isLoading: true
@hyamakawa 
該当箇所について修正しました。
※「Webアプリ開発」の「4-6. 非同期処理を同期処理に変え、ローディング機能を取り入れる」で対応した形に合わせた為、上記のような対応となりました。

2022-08-24 10:45 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +    onClickEditIcon (bookList) {
@hyamakawa 
該当箇所について修正しました。

2022-08-24 12:31 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +        {{ bookList.buyer }}
@hyamakawa 
>>36行目の <v-menu から63行目 </menu>までのdatepickerの使い方、合ってないようにみえるんですよね。
→合ってないようには見えないですが、具体的に何行目が合ってないでしょうか？ちなみに58行目～60行目は今回の対応用に追加しています。

2022-08-24 13:44 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +        {{ bookList.buyer }}
@hyamakawa 
>>コメントにつけた参考サイト見ていただけてます？違う対応内容になるかと思います。

⇒95行目～98行目は削除しました。

2022-08-24 13:46 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +        item-text="category"
@hyamakawa 
「searchCategory」には「item-value」の値が入る認識です。

2022-08-24 13:55 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +    this.isLoading = false
@hyamakawa 
該当箇所について修正しました。

2022-08-24 13:56 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +        <td>{{ bookList.buyer }}</td>
@hyamakawa 
95行目～98行目は削除しました。

2022-08-24 14:06 UTC, nishinoa commented
@山川宏賢@yanagi-m@田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-08-24 14:34 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +        item-text="category"
@nishinoa 意図してitem-valueの設定を外していたわけではないということですかね。承知しました。

2022-08-24 14:39 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +      dialogBookList: {},
こちらも 変数名を変更した方がよろしいかと思いました。
変数名である程度、どういう値が設定される項目なのか分かると可読性も上がるので。
listだと中身が配列だと勘違いしてしまいますよね。

2022-08-24 14:57 UTC, hyamakawa commented
> 合ってないようには見えないですが、具体的に何行目が合ってないでしょうか？ちなみに58行目～60行目は今回の対応用に追加しています。

一番気になっているのは `dialogBookList.purchase_date` `pickerDate` と2つの日付が入りそうな変数が登場しているところです。なぜ2つを使わないといけなかったので理解できませんでした。。どういう流れで画面から選択した値がそれぞれの変数に入っていくのか教えてください🙏

⬇︎が公式サイトにある西埜さんが今回実現したいものに近いソースです。
``` javascript 
<v-menu
  v-model="menu2"
  :close-on-content-click="false"
  :nudge-right="40"
  transition="scale-transition"
  offset-y
  min-width="auto"
>
  <template v-slot:activator="{ on, attrs }">
    <v-text-field
      v-model="date"
      label="Picker without buttons"
      prepend-icon="mdi-calendar"
      readonly
      v-bind="attrs"
      v-on="on"
    ></v-text-field>
  </template>
  <v-date-picker
    v-model="date"
    @input="menu2 = false"
  ></v-date-picker>
</v-menu>
```

⬇︎が西埜さんのソースです
``` javascript
<v-menu
  ref="menu"
  v-model="menu"
  :close-on-content-click="false"
  :return-value.sync="pickerDate"
  transition="scale-transition"
  offset-y
  min-width="auto"
>
  <template #activator="{ on, attrs }" >
    <v-text-field
      v-model="dialogBookList.purchase_date"
      label="購入日"
      prepend-icon="mdi-calendar"
      readonly
      v-bind="attrs"
      v-on="on"
    />
  </template>
  <v-date-picker
    v-model="pickerDate"
    no-title
    scrollable
    @input="dialogBookList.purchase_date = pickerDate
    $refs.menu.save(pickerDate)
    menu = false
    "
  />
</v-menu>
```

2022-08-24 15:01 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +      dialogBookList: {},
@hyamakawa 
「dialogBookList」から「dialogBook」に変更しました。

2022-08-24 15:03 UTC, nishinoa commented
@山川宏賢@yanagi-m@田中みつき
頂いた指摘事項の取込（3回目）を行いましたので、ご確認の程よろしくお願いします。

2022-08-24 15:50 UTC, nishinoa commented
@hyamakawa 
>>一番気になっているのは dialogBookList.purchase_date pickerDate と2つの日付が入りそうな変数が登場しているところです。なぜ2つを使わないといけなかったので理解できませんでした。。どういう流れで画面から選択した値がそれぞれの変数に入っていくのか教えてください🙏

⇒最初、「v-date-picker」の日付を「YYYY-MM-DD」から「YYYYMMDD」に形式変換する為に変数を2つに分けていましたが、形式変換しないようにしたので分ける必要ないですね。

2022-08-24 15:54 UTC, nishinoa commented
@山川宏賢@yanagi-m@田中みつき
頂いた指摘事項の取込（4回目）を行いましたので、ご確認の程よろしくお願いします。
※「pickerDate」の変数を削除して、「dialogBook.purchase_date」に変更しました。

2022-08-25 02:13 UTC, hyamakawa approved these changes
@nishinoa 

lgtm🍦おつかれさまでした。
若干きになるところが2つありますが、また後で対応でもいいかなと思うので、ネクストステージに進んでくださいっ！

＜気になるところ＞
・bookList内のプロパティ名がスネーク
・v-row、v-colをもう少し入れたい

2022-08-25 11:09 UTC, merged