Webアプリ開発2（3-2-4）
nishinoa/test1 pull request #20
Opened 2022-08-28 08:24 UTC by nishinoa

@山川宏賢@yanagi-m@田中みつき  
Webアプリ開発2の「2-4. BookApp.vueのロジックをList.vue,Search.vue,Form.vueに分割する」について対応しましたので、ご確認の程よろしくお願いします。
※分割前に比べ、「新規登録」ボタンの配置位置が若干変わっています。

![image](https://user-images.githubusercontent.com/92168753/187064872-c77c8b08-0b7b-4e1a-ab83-546579dbe12a.png)

2022-08-29 09:25 UTC, hyamakawa requested changes
@nishinoa 

確認しました。コメントしたのでご確認・ご対応よろしくお願いいたします。
コンポーネントするときのポイントは、

・誰がどんな役割を持ってるのか具体的に考えることと
・その役割を遂行する上でデータを冗長に扱わずにどうやって管理するのか

というところかなとレビューして思いました。

2022-08-29 09:25 UTC, hyamakawa commented on web_application_2/src/components/Form.vue
> +    <v-dialog v-model="isShowDialog" max-width="500px">
listでもformでもisShowDialogを意識しないといけないのが少し冗長かなと思いました。
v-dialogをlist側に持っていくのはどうでしょうか。

2022-08-29 09:25 UTC, hyamakawa commented on web_application_2/src/components/Form.vue
> +    <v-dialog v-model="isShowDeleteDialog" max-width="500px">
formコンポーネントと削除ダイアログは無関係なものですよね、おそらく。

なので、こちらにコードがあるのは違うかなと思いました。

2022-08-29 09:25 UTC, hyamakawa commented on web_application_2/src/components/List.vue
> +      this.dialogBook = {}
ここで `this.dialogBook ` を初期化している理由はなんでしょうか。

2022-08-29 09:25 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +    </search-template>
終わりタグはいらないと思います。

```
<search-template
...
...
/ >
```

2022-08-29 09:25 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +    </list-template>
終わりタグはいらないと思います。

```
<list-template
...
...
/ >
```

2022-08-29 09:25 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
>        bookList: [
bookListはBookApp.vueが管理しているので、登録ダイアログ、編集ダイアログ、削除ダイアログも全てBookApp .vueに紐づけた方が、bookListを編集しやすいのかなと思いましたがいかがでしょうか。
今のままだとbookListを管理しているのが誰なのか少し分かりずらいなと思いました。

もしBookAppに全て紐づけると下記のようになるかなと思います。
例：ListからFormの呼び出しをやめて、FormはBookAppからの呼び出しに変える
例：編集の時はListからemitして、BookAppを経由して、Formを呼び出し、クリックしたbookデータをFormに渡す

2022-08-29 12:22 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +    </search-template>
@hyamakawa 
該当箇所について修正しました。

2022-08-29 12:22 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +    </list-template>
@hyamakawa 
該当箇所について修正しました。

2022-08-29 12:52 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
>        bookList: [
@hyamakawa 
「v-data-table」をListに持ってくるとして、「v-dialog」は「v-data-table」タグの中に入れないとうまく動かないと思いますが、全てBookAppから呼び出して実現できるのでしょうか？

（List.vue）
<v-data-table>
・・・・・　　　　←この中にダイアログ（v-dialog）がないと登録、編集、削除ダイアログが表示されない
</v-data-table>

2022-08-29 13:11 UTC, nishinoa commented on web_application_2/src/components/List.vue
> +      this.dialogBook = {}
@hyamakawa 
ダイアログを閉じる処理（キャンセル）なので、選択した書籍情報を念の為クリアしています。

2022-08-29 13:17 UTC, nishinoa commented on web_application_2/src/components/Form.vue
> +    <v-dialog v-model="isShowDeleteDialog" max-width="500px">
@hyamakawa 
「v-data-table」をList.vueに持ってくるとして、「v-dialog」は「v-data-table」タグの中に入れないとうまく動かないと思いますが、削除ダイアログをBookAppから呼び出すようにしてうまく動きますか？

2022-08-29 13:20 UTC, nishinoa commented on web_application_2/src/components/Form.vue
> +    <v-dialog v-model="isShowDialog" max-width="500px">
@hyamakawa 
v-dialogをList.vueに持ってくるとして、Form.vueは<v-card>～</v-card>になりますか？

2022-08-30 03:22 UTC, hyamakawa commented on web_application_2/src/components/Form.vue
> +    <v-dialog v-model="isShowDialog" max-width="500px">
@nishinoa はい、そのイメージです。

2022-08-30 03:30 UTC, hyamakawa commented on web_application_2/src/components/Form.vue
> +    <v-dialog v-model="isShowDeleteDialog" max-width="500px">
@nishinoa 

v-dialogとv-data-tableに密接な関係はないので、切り離しはできると思います。
あとは、v-dialogの表示・非表示を制御している、 v-model="isShowDeleteDialog" を
誰が制御するのか決められれば解決できそうです。

例えば、削除ダイアログをBookApp.vueで持つとしたら、isShowDeleteDialogもBookApp.vueで持つことになりますよね。なので、listの削除アイコンを押した時に、BookApp.vueで持ってるisShowDeleteDialogを編集できればいい、ということになるのかなと思います。

伝わりましたでしょうか。。文章で伝えるの難しい。

2022-08-30 03:36 UTC, hyamakawa commented on web_application_2/src/components/List.vue
> +      this.dialogBook = {}
@nishinoa 

念の為ということで承知しました。そのままでもOKですが、個人的にはあまり意味のないロジックは残したくないです。
意味のあるロジックと念の為ロジックが混じってると、見分けがつかなくなって、修正が入った時に「これなんだっけ？なんか意味あるんだっけ？消したいけど、わかんないからとりあえず残しとくか」みたいな感じで意味のないロジックが増えていくことにもつながるためです。
もし残す場合は、コメントなど入れておくといいんですかね。

2022-08-30 03:36 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +    </search-template>
🙆

2022-08-30 03:36 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +    </list-template>
🙆

2022-08-30 03:37 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
>        bookList: [
@nishinoa 

> 「v-data-table」をList.vueに持ってくるとして、「v-dialog」は「v-data-table」タグの中に入れないとうまく動かないと思いますが、全てBookAppから呼び出して実現できるのでしょうか？

実現できると思います。
他のコメントにも書きましたが、「v-dialog」は「v-data-table」に紐付きはありません。

2022-08-30 12:26 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
>        bookList: [
@hyamakawa 
伝え方がまずかったです。
まず、自分の認識として＜v-data-table＞タグの中に＜template v-slot:top＞タグがないといけないと思っています。
※＜v-data-table＞と＜template v-slot:top＞に紐付きがある認識。
そして、＜template v-slot:top＞タグの中に＜v-dialog＞タグがないといけないと思っているのですが、認識誤ってますか？

2022-08-31 10:54 UTC, nishinoa commented
@山川宏賢@yanagi-m@田中みつき
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

2022-08-31 12:37 UTC, nishinoa commented on web_application_2/src/components/List.vue
> +      this.dialogBook = {}
@hyamakawa 
該当箇所を削除しました。

2022-09-01 04:15 UTC, hyamakawa commented on web_application_2/src/components/List.vue
> +      this.dialogBook = {}
🙆

2022-09-01 05:04 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
>        bookList: [
@nishinoa 

> ＜v-data-table＞と＜template v-slot:top＞に紐付きがある認識。

この認識は合ってます🙆
でも、＜v-dialog＞を使うときは ＜template v-slot:top＞ の中にいれないと使えない、ということにはなりません。
<v-dialog>は ＜template v-slot:top＞ の外にあっても、v-modelが trueであれば出てくるし、falseであれば消えます。
ポイントはv-modelなので、それが制御できればどこにタグがあってもOKですっ。

v-slot自分もそこまで詳しくないですが、＜template v-slot:top＞を使ってるイメージとしては、v-datatableでは内部でtopというものを持っていて、そのtopを＜template v-slot:top＞タグ内に書いた内容で上書きしてる感じです。

2022-09-02 06:41 UTC, hyamakawa requested changes
@nishinoa 確認しました。コメントしたのでご確認・ご対応よろしくお願いします。

2022-09-02 06:41 UTC, hyamakawa commented on web_application_2/src/components/List.vue
> +      this.$emit('onClickEditIcon', this.dialogBook)
data部に宣言されている変数に設定する必要ありますでしょうか。
変数に入れずに直接 `Object.assign({}, book)` を返しちゃう、もしくは宣言したい場合は関数内でconst宣言すればよいのかなと思いました。

2022-09-02 06:43 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +          @onClickInsertUpdateBtn="onClickInsertUpdateBtn"
インデント右にいきすぎ？

2022-09-02 06:44 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +     <v-card>
削除ダイアログも別コンポーネント化してもいいなと思いました。
どうするかはお任せしますっ。

2022-09-02 06:46 UTC, hyamakawa commented
@nishinoa 確認終わりましたっ、スッキリした感があります。お疲れ様でしたっ🐇残りコメントをご確認くださいっ。

2022-09-02 06:59 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +     <v-card>
@hyamakawa 
削除ダイアログも別コンポーネント化すると、「プロジェクト土台の説明」のイメージ図と乖離する為、今回はこのままにしようと思います。
※「Webアプリ開発2」が全て完了して、余裕があったらやってみてもいいかもしれません。

2022-09-02 07:11 UTC, nishinoa commented on web_application_2/src/view/BookApp.vue
> +          @onClickInsertUpdateBtn="onClickInsertUpdateBtn"
@hyamakawa 
該当箇所について修正しました。

2022-09-02 07:25 UTC, nishinoa commented on web_application_2/src/components/List.vue
> +      this.$emit('onClickEditIcon', this.dialogBook)
@hyamakawa 
該当箇所について修正しました。

2022-09-02 07:28 UTC, nishinoa commented
@山川宏賢@yanagi-m@田中みつき
頂いた指摘事項の取込（2回目）を行いましたので、ご確認の程よろしくお願いします。

2022-09-02 22:04 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +     <v-card>
🙆

2022-09-02 22:04 UTC, hyamakawa commented on web_application_2/src/view/BookApp.vue
> +          @onClickInsertUpdateBtn="onClickInsertUpdateBtn"
🙆

2022-09-02 22:04 UTC, hyamakawa commented on web_application_2/src/components/List.vue
> +      this.$emit('onClickEditIcon', this.dialogBook)
🙆

2022-09-02 22:05 UTC, hyamakawa commented
@nishinoa lgtm🦔お疲れ様でしたっ

2022-09-03 02:51 UTC, merged