Webアプリ開発（1-3）
nishinoa/test1 pull request #9
Opened 2022-05-22 08:06 UTC by nishinoa

@山川宏賢 @片岡亮[@u-hashi](https://github.com/u-hashi)@ma-yamashita  
Webアプリ開発の「1-3. 見た目をいい感じにしてみる」について対応を行いましたので、 ご確認の程、よろしくお願いします。

2022-05-23 06:35 UTC, hyamakawa requested changes
課題、お疲れ様です！
確認しました、対応よろしくお願いしますっ。

※今度からで構いませんので、画面の見た目を修正する場合はプルリクで画面のスクショを貼ってもらえるとうれしいです。

2022-05-23 06:35 UTC, hyamakawa commented on webdevelop/index.html
> +      <input type="text" id="textbox" value="0"><br><br>
前回のプルリクで気づけなくて申し訳ないのですが、部品の間隔をあけるのに<br>は使わなさそうです。

<br>の使い所としては、文章を改行するとき、です。
部品の場合はパディング、マージングをCSSでいじる感じになると思います。

2022-05-23 06:35 UTC, hyamakawa commented on webdevelop/index.html
> +      <input type="text" id="textbox" value="0"><br><br>
せっかくなので、中身を編集できないようにCSSで指定してみませんか。
文字を入力してカウントアップすると `NaN` になっちゃうので。

2022-05-23 06:35 UTC, hyamakawa commented on webdevelop/index.html
> +    <style>
　おしゃれになりましたね！

2022-05-23 13:15 UTC, nishinoa commented
@山川宏賢 @片岡亮[@u-hashi](https://github.com/u-hashi)@ma-yamashita
Webアプリ開発の「1-3. 見た目をいい感じにしてみる」について、
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

[画面キャプチャ.xlsx](https://github.com/nishinoa/test1/files/8754796/default.xlsx)

2022-05-24 02:39 UTC, hyamakawa requested changes
対応ありがとうございます。
再度コメントしたのでご確認・対応よろしくお願いします。

2022-05-24 02:39 UTC, hyamakawa commented on webdevelop/index.html
> +      <p>カウントアップアプリ</p>
インデント、右に一つ下げたほうがいいですかね？

2022-05-24 02:39 UTC, hyamakawa commented on webdevelop/index.html
> +      <p>カウントアップアプリ</p>
3つのinputタグもdivの中にいるので、右に1つインデント下げたほうがよさそうですね。
ちなみに、divで囲んでる理由はなんでしょうか？

2022-05-24 02:46 UTC, hyamakawa commented
@nishinoa 

また画像の添付ですが、エクセルに貼り付けなくても、githubのコメント欄にドラッグ＆ドロップしたり、欄下にある `attach files ...` のところをクリックすると画像を添付できますよ。

2022-05-24 13:12 UTC, nishinoa commented
@山川宏賢 @片岡亮[@u-hashi](https://github.com/u-hashi)@ma-yamashita
Webアプリ開発の「1-3. 見た目をいい感じにしてみる」について、
頂いた指摘事項の取込を行いましたので、ご確認の程よろしくお願いします。

![image](https://user-images.githubusercontent.com/92168753/170042865-b9d9b927-32cb-48e8-9f18-3c13e86d0119.png)

2022-05-24 22:41 UTC, hyamakawa commented
@nishinoa 

対応内容は確認しました、OKです。

> ちなみに、divで囲んでる理由はなんでしょうか？

こちらはいかがでしょうか。

2022-05-25 10:45 UTC, nishinoa commented
@山川宏賢
昨日、slackのスレッドで返信したのですが、見て頂けていないようなので
こちらでも回答します。

>ちなみに、divで囲んでる理由はなんでしょうか？
部品と部品の間に改行を入れる為（部品を縦に並べる為）にdivで囲みました。brは文章を改行する時に使う的なコメントを頂いたので。

2022-05-25 10:47 UTC, nishinoa commented
@山川宏賢
昨日、slackのスレッドで返信したのですが、見て頂けていないようなので
こちらでも回答します。

>ちなみに、divで囲んでる理由はなんでしょうか？

部品と部品の間に改行を入れる為（部品を縦に並べる為）にdivで囲みました。brは文章を改行する時に使う的なコメントを頂いたので。

2022-05-25 22:12 UTC, hyamakawa commented
@nishinoa 

> 部品と部品の間に改行を入れる為（部品を縦に並べる為）にdivで囲みました。brは文章を改行する時に使う的なコメントを頂いたので。

divタグにそんな機能があったんですね、ただのグループ化タグだと認識してました。
動き確かめてみたら、確かに横に並びましたね。

> 昨日、slackのスレッドで返信したのですが、見て頂けていないようなので

確かにされてますね、失礼しました。
GitHubのbotの投稿に返信する場合は未読表示されないので、
メンションしないと気づくのむずかしいっぽいです。
なので、GitHubのbotの投稿に返信する場合はメンションしていただけると嬉しいです 🙇

2022-05-25 22:13 UTC, hyamakawa commented
LGTM 🙆‍♂️

2022-05-26 10:51 UTC, merged